version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - database.dev.env
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
